name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=5s --health-timeout=3s --health-retries=5

    steps:
    - uses: actions/checkout@v4

    - name: Set up .env for CI/CD
      run: |
        cp .env.example .env
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=127.0.0.1" >> .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=test_db" >> .env
        echo "DB_USERNAME=test_user" >> .env
        echo "DB_PASSWORD=test_password" >> .env

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Create MySQL User for CI/CD
      run: |
        mysql -h 127.0.0.1 -u root -prootpassword -e "CREATE USER 'ci_user'@'%' IDENTIFIED BY 'ci_password';"
        mysql -h 127.0.0.1 -u root -prootpassword -e "GRANT ALL PRIVILEGES ON test_db.* TO 'ci_user'@'%';"
        mysql -h 127.0.0.1 -u root -prootpassword -e "FLUSH PRIVILEGES;"

    - name: Run Migrations
      run: php artisan migrate --force

    - name: Execute Tests
      run: php artisan test

    - name: Drop Temporary MySQL User
      run: |
        mysql -h 127.0.0.1 -u root -prootpassword -e "DROP USER 'ci_user'@'%';"
